config/routes.rb
Rails.application.routes.draw do
  root controller: "submissions", action: "index"

  resources :submissions, except: [:show, :edit, :update, :destroy]
  resources :comments, except: [:show, :edit, :update, :destroy]
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  get "comments/:submission_id", controller: "comments", action: "index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :submission
  belongs_to :user

  def timestampdiff
    diff = Time.now - self.comment_time
    # TODO fix the /s and specify cases for one day/hour/minute
    if diff / 86_400 > 1
      "#{(diff / 86_400).to_i} day/s ago"
    elsif diff / 3600 > 1
      "#{(diff / 3600).to_i} hour/s ago"
    elsif diff / 3600 < 1 && diff / 60 > 1
      "#{(diff / 60).to_i} minute/s ago"
    else
      "less than one minute ago"
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  has_many :comments
  belongs_to :user

  def timestampdiff
    diff = Time.now - self.submission_time
    # TODO fix the /s and specify cases for one day/hour/minute
    if diff / 86_400 > 1
      "#{(diff / 86_400).to_i} day/s ago"
    elsif diff / 3600 > 1
      "#{(diff / 3600).to_i} hour/s ago"
    elsif diff / 3600 < 1 && diff / 60 > 1
      "#{(diff / 60).to_i} minute/s ago"
    else
      "less than one minute ago"
    end
  end

  def submission_username
    user = User.find_by(self.user_id)
    user.username
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(plaintext_password)
    @password = BCrypt::Password.create(plaintext_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find_by(id: session[:current_user_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.new
    @comments = Comment.where(submission_id: params[:submission_id]).order(comment_time: :desc)
    @submission = Submission.find(params[:submission_id])
  end

  def create
    extra_params = { comment_time: Time.now, user_id: current_user.id }
    params = comment_params.merge(extra_params)
    @comment = Comment.new(params)
    @comment.save
    redirect_to "/"
  end

  private def comment_params
    params.require(:comment).permit(:comment_text, :submission_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      session[:current_user_id] = @user.id
      redirect_to submissions_path
    else
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to new_sessions_path
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authorize!, except: [:index]
  def index
    @submissions = Submission.all.order(submission_time: :desc)
    @comments = Comment.all
  end

  def new
    @submission = Submission.new
  end

  def create
    extra_params = { submission_time: Time.now, user_id: current_user.id }
    params = submission_params.merge(extra_params)
    @submission = Submission.new(params)

    if @submission.save
      session[:success] = "Link submitted!"
      redirect_to submissions_path
    else
      session[:error] = "Link could not be submitted, please fill out all required fields"
      render "new"
    end
  end

  private def submission_params
    params.require(:submission).permit(:link, :title)
  end

  private def authorize!
    unless current_user
      flash[:error] = "Please log in"
      redirect_to new_sessions_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = user_params[:username]
    @user.email = user_params[:email]
    @user.password = user_params[:password]
    @user.password_confirmation = user_params[:password_confirmation]

    if @user.save
      redirect_to "/"
    else
      render "new"
    end
  end

  private def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_area :comment_text, size: "60x10" %>
   <%= hidden_field_tag "comment[submission_id]", "#{@submission.id}" %>
  <%= f.submit "save" %>
<% end %>

<ul>
  <% @comments.each do |comment| %>
    <li class="tag">Posted <%= comment.timestampdiff %> by <%= comment.user&.username %></li>
    <li><%= comment.comment_text %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freddit: the backpage of the internet</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "top">
        MY SUBREDDITS <c>&#9660</c>
        <a href="/">
          <span>HOME</span>
        </a>
         - POPULAR - ALL - RANDOM - ASKREDDIT - FUNNY - PICS - WORLDNEWS - VIDEOS - NEWS - TODAYILEARNED - GAMING - MOVIES - GIFS - AWW - MILDLYINTERESTING - SHOWERTHOUGHTS - IAMA - JOKES - TELEVISION - OLD<b> &nbsp EDIT » </b>
      </nav>
      <a href="/">
        <img class= "logo" src="https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Reddit_logo_and_wordmark.svg/1280px-Reddit_logo_and_wordmark.svg.png" alt="">
      </a>
      <nav class= "logobar">
        <span id="current">hot</span>
        new rising controversial top gilded wiki promoted
        <% if current_user %>
          <p id="login_or_signup"> <%= current_user.username %> | <%= link_to "logout", sessions_path, method: :delete %></p>
        <% else %>
          <p id="login_or_signup">
             Want to join?
             <a href= <%= new_sessions_path %> >
               Log in
             </a>
             or 
             <a href= <%= new_user_path %> >sign up</a>
             in seconds.&nbsp|
             <a><b>English</b></a>
          </p>
        <% end %>
      </nav>
    </header>
    <main>
      <%= flash[:error] %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/submissions/index.html.erb
<ol>
  <% @submissions.each do |submission| %>
    <li><%= link_to "#{submission.title}", "#{submission.link}"%>
      <p class="time"> submitted <%= submission.timestampdiff %> by <%= submission.user&.username %></p>
      <p class="comments"><%= link_to "#{submission.comments.count} comments", comments_url(submission_id: submission.id)%></p>
    </li>
  <% end %>
</ol>

<span class="submit"><%= link_to("Submit a new link", action: "new") %></span>

app/views/submissions/new.html.erb
submit to freddit

<%= form_for @submission do |f| %>

  <%= f.label :link %>
  <%= f.text_field :link, required: true %>

  <%= f.label :title %>
  <%= f.text_field :title, required: true%>

  <%= f.submit "submit"%>

<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, required: true %>

  <%= f.label :password %>
  <%= f.password_field :password, required: true %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, required: true %>

  <%= f.submit "submit", id: "button"%>

<% end %>